/**
 * HER HANDWRITTEN SCROLL LIST (141 REASONS & LOVE NOTES)
 * Exactly transcribed from her handwritten folded paper strip gift,
 * preserving all exact numbering, typos, and phrasing, paired with Vishal's replies.
 */

const HER_SCROLL_LIST = [
  {"id": 1, "number": "1.", "text": "V for vishal  V for victory", "reply": "And you are my greatest victory in life, hands down. ❤️", "reaction": "🏆"},
  {"id": 2, "number": "2.", "text": "Thank you for being there for me", "reply": "Always, my love. Through every storm, every late night, and every single day—I will always be right beside you.", "reaction": "🛡️"},
  {"id": 3, "number": "3.", "text": "you are the cutest", "reply": "Look who is talking! Your little pout and adorable giggles win every single time. 🌸", "reaction": "🥰"},
  {"id": 4, "number": "4.", "text": "you are the sweetest", "reply": "Only because you bring out the gentlest and softest part of my heart. 🍬", "reaction": "🍯"},
  {"id": 5, "number": "5.", "text": "you are my fav person ever", "reply": "And you are mine—in this room, in this city, in this entire universe. 💖", "reaction": "✨"},
  {"id": 6, "number": "6.", "text": "I will never leave you", "reply": "Promise held tight. You couldn't get rid of me even if you tried. 🤝", "reaction": "🔒"},
  {"id": 7, "number": "7.", "text": "you also never breakup with me", "reply": "Never in a million lifetimes. You are stuck with me forever, deal with it! 💍", "reaction": "♾️"},
  {"id": 8, "number": "8.", "text": "you are my fav snotification", "reply": "Every time my screen lights up with your name, my whole face lights up too. 📱", "reaction": "🔔"},
  {"id": 9, "number": "9.", "text": "Being with makes everything better", "reply": "Even getting on the wrong bus in the freezing cold felt like magic because you were holding my hand. 🚌", "reaction": "🪄"},
  {"id": 10, "number": "10.", "text": "Still choosing you everyday", "reply": "And I will choose you tomorrow, next week, in 50 years, over and over again without a second thought.", "reaction": "🌅"},
  {"id": 11, "number": "11.", "text": "you make ordinary days feel special", "reply": "With you, eating street food or doing laundry feels like an anniversary date. 🌟", "reaction": "☕"},
  {"id": 12, "number": "12.", "text": "you're lucky you are cute", "reply": "Phew! Thank goodness my cuteness saves me from your wrath! 😇", "reaction": "🍀"},
  {"id": 13, "number": "13.", "text": "you are my fav headache", "reply": "Haha! You give me headaches and then cure them with one single cuddle. 🤕❤️", "reaction": "💆‍♂️"},
  {"id": 14, "number": "14.", "text": "It's you it's always you", "reply": "From that unfinished chess game on day one, my heart already knew. It has always been you. ♟️", "reaction": "🎯"},
  {"id": 15, "number": "15.", "text": "If home was a person I'd be you", "reply": "Your arms are the only place in the world where my soul feels completely at peace. 🏡", "reaction": "🤍"},
  {"id": 16, "number": "16.", "text": "you're annoying but sadly, irreplacable.", "reply": "Haha! Sadly?! You love my annoying self and you know it! Irreplaceable is right. 😜", "reaction": "👑"},
  {"id": 17, "number": "17.", "text": "you are the one for me", "reply": "And I thank the universe every single night that I found you. 🌌", "reaction": "🌠"},
  {"id": 18, "number": "18", "text": "I don't have any secrets b/w us", "reply": "I love how open we are. You know every thought, fear, and silly dream in my head.", "reaction": "🗝️"},
  {"id": 19, "number": "19", "text": "I don't need anyone else but you", "reply": "Just you and me against the whole wide world. That's all I'll ever need. 🌍", "reaction": "👫"},
  {"id": 20, "number": "20", "text": "you are my comfort person", "reply": "Whenever the world gets overwhelming, one hug from you makes all the noise disappear. 🫂", "reaction": "🧸"},
  {"id": 21, "number": "21", "text": "you are the one i look for everywhere", "reply": "In a crowded room or a noisy street, my eyes instinctively search for your smile first.", "reaction": "👀"},
  {"id": 22, "number": "22", "text": "I don't think I even deserve you", "reply": "Hey, don't you dare say that. You deserve the stars, the moon, and all the love I have to give. 🥺", "reaction": "💫"},
  {"id": 23, "number": "23", "text": "I hope I never get sick of you", "reply": "I promise to keep being charming, funny, and annoying enough so that you never do! 😂", "reaction": "💊"},
  {"id": 24, "number": "24", "text": "I keep falling more everyday for you", "reply": "Me too. Just when I think I couldn't possibly love you more, you smile at me and prove me wrong.", "reaction": "🍂"},
  {"id": 25, "number": "25", "text": "Everything I do is for you", "reply": "Seeing you proud and happy is the fuel behind everything I work hard for.", "reaction": "🔥"},
  {"id": 26, "number": "26", "text": "I can never get enough of you", "reply": "Good, because you're on a lifetime subscription with no cancellation policy! 📜", "reaction": "♾️"},
  {"id": 27, "number": "27", "text": "you make me happy", "reply": "Your laughter is literally my favorite sound on this planet. 🎶", "reaction": "😄"},
  {"id": 28, "number": "28", "text": "10/10 bf  3/10 decision maker", "reply": "EXCUSE ME!! I made the best decision in history when I chose you! That automatically makes it 100/10! 😂❤️", "reaction": "📊"},
  {"id": 29, "number": "29", "text": "I'm literally obsessed with you", "reply": "And I am completely, utterly head-over-heels for you. 💫", "reaction": "🌀"},
  {"id": 30, "number": "30", "text": "you are my fav inconvinience", "reply": "The sweetest inconvenience I could ever ask for. Call me at 3 AM anytime. 📞", "reaction": "🌙"},
  {"id": 31, "number": "31", "text": "you look better with me", "reply": "Facts! We look gorgeous together. S-tier couple aesthetic. 📸", "reaction": "💎"},
  {"id": 32, "number": "32", "text": "I'd always find my way back to you", "reply": "No matter where life takes us, all my compasses point straight to you. 🧭", "reaction": "⚓"},
  {"id": 33, "number": "33", "text": "you make it all so easy", "reply": "Loving you is as effortless as breathing. It's the most natural thing in the world.", "reaction": "🍃"},
  {"id": 34, "number": "34", "text": "I'm glad it's with you", "reply": "I wouldn't want to live this adventure with anyone else on earth. 🚢", "reaction": "🥂"},
  {"id": 35, "number": "35", "text": "I need you today tomorrow always", "reply": "Today, tomorrow, and every single day that follows—I'm right here. 🗓️", "reaction": "♾️"},
  {"id": 36, "number": "36", "text": "I still have a hard crush on you", "reply": "Good, because the butterflies in my stomach still flutter every time you look my way. 🦋", "reaction": "💓"},
  {"id": 37, "number": "37", "text": "Even when we argue I love you", "reply": "Even when we disagree or pout, you're still the only one I want to talk to five minutes later.", "reaction": "🕊️"},
  {"id": 38, "number": "38", "text": "I like us, a lot.", "reply": "I love us, endlessly. We are something truly special. 🌟", "reaction": "💞"},
  {"id": 39, "number": "39", "text": "you're my kind of chaos", "reply": "And you bring just the right amount of wild beauty into my life. 🌪️", "reaction": "🎨"},
  {"id": 40, "number": "40", "text": "you are so worth it", "reply": "Every sacrifice, every late night, every wait—you are worth every single second. ⏳", "reaction": "🏆"},
  {"id": 41, "number": "41", "text": "you are stuck with me now", "reply": "Best trap I ever fell into. I threw the key away! 🗝️", "reaction": "🕸️"},
  {"id": 42, "number": "42", "text": "Somehow you became my person.", "reply": "From classmates who barely talked, to unfinished chess, to my whole entire heart. 📖", "reaction": "♟️"},
  {"id": 43, "number": "43", "text": "I'd marry you with paper rings", "reply": "Paper rings, string, or gold—I'd say yes in a heartbeat. 💍", "reaction": "🎀"},
  {"id": 44, "number": "44.", "text": "you just get me", "reply": "I see through your masks, your silences, and your moods—and I love every layer. 🔮", "reaction": "💡"},
  {"id": 45, "number": "45", "text": "you know me inside and out.", "reply": "And every single piece I discover makes me fall even deeper. 🧩", "reaction": "🔍"},
  {"id": 46, "number": "46", "text": "you know my issues and still choose me", "reply": "Your quirks and vulnerabilities don't scare me; they make you human and uniquely yours. 🛡️", "reaction": "🫂"},
  {"id": 47, "number": "47", "text": "I'd love you if you were a worm", "reply": "Hahaha! The ultimate test of love! I'd build you the coziest little garden terrarium and feed you fresh leaves every day! 🪱❤️", "reaction": "🌱"},
  {"id": 48, "number": "48", "text": "I hate how much I like you", "reply": "You can't fight it anymore! Surrender to the love! 😈❤️", "reaction": "💥"},
  {"id": 49, "number": "49", "text": "I blame you for this attachment", "reply": "I take full, proud responsibility for making you fall for me. 😌", "reaction": "🔗"},
  {"id": 50, "number": "50", "text": "I love being with you.", "reply": "There is nowhere else in the entire world I'd rather be. 🗺️", "reaction": "🏝️"},
  {"id": 51, "number": "51", "text": "you make me fell so safe", "reply": "Keeping you safe, warm, and cherished is my highest sacred duty. 🛡️", "reaction": "🕯️"},
  {"id": 52, "number": "52", "text": "you always know exactly wt to say", "reply": "Even when I don't, I just speak straight from my heart to yours. 💬", "reaction": "📜"},
  {"id": 53, "number": "53", "text": "you never let me feel I am too much", "reply": "You are never 'too much' for the person who can never get enough of you. 🌊", "reaction": "💖"},
  {"id": 54, "number": "54", "text": "you feel familier in the best way", "reply": "Like coming home after a long journey in the rain. 🌧️", "reaction": "🛋️"},
  {"id": 55, "number": "55", "text": "you love me for me", "reply": "Unconditionally, completely, and without ever asking you to be anyone else. 🪞", "reaction": "👑"},
  {"id": 56, "number": "56", "text": "you make it all so easy", "reply": "Because with true love, nothing has to be forced. It just flows. 🌊", "reaction": "⛵"},
  {"id": 57, "number": "57", "text": "I love being yours, always", "reply": "And having you as mine is the greatest honor of my life. 🏷️", "reaction": "💝"},
  {"id": 58, "number": "58", "text": "I'll be with you, always and forever", "reply": "A promise sealed in our hearts, written in stone, and kept forever. ♾️", "reaction": "⏳"},
  {"id": 59, "number": "59", "text": "you're my kind of guy", "reply": "And you're my dream girl in real life. 🌟", "reaction": "🕶️"},
  {"id": 60, "number": "60", "text": "you are my fav constant", "reply": "In a world where everything changes, you are my steady anchor. ⚓", "reaction": "🏛️"},
  {"id": 61, "number": "61", "text": "my fav human", "reply": "My favorite creature, my favorite smile, my favorite company. 🐾", "reaction": "🧸"},
  {"id": 62, "number": "62", "text": "you feel like mine", "reply": "Because I belong to you, and you belong to me. 🔒", "reaction": "🗝️"},
  {"id": 63, "number": "63", "text": "hey handsome", "reply": "Hey gorgeous girl with the enchanting eyes! 😉", "reaction": "🌹"},
  {"id": 64, "number": "64", "text": "shhh... you are mine", "reply": "Yes ma'am! Completely surrendered and happily claimed. 🤫❤️", "reaction": "🤐"},
  {"id": 65, "number": "65", "text": "we are soulmates", "reply": "I never believed in soulmates until our stories collided and fit together like puzzle pieces. 🧩", "reaction": "✨"},
  {"id": 66, "number": "66", "text": "we are made for each other", "reply": "Handcrafted by fate, polished by time, and destined to be together. 🔨", "reaction": "💎"},
  {"id": 67, "number": "67", "text": "I'm so lucky to have you", "reply": "I am the one who won the cosmic lottery the day you walked into my life. 🎰", "reaction": "🍀"},
  {"id": 68, "number": "68", "text": "I love being yours", "reply": "Hearing you say that gives me goosebumps every single time. 💓", "reaction": "🥰"},
  {"id": 69, "number": "69", "text": "I am happiest with you", "reply": "Seeing your crinkled nose and bright smile is the highlight of my every waking day. 😊", "reaction": "☀️"},
  {"id": 70, "number": "70", "text": "I am always rooting for you", "reply": "Knowing you believe in me makes me feel like I can conquer any obstacle in this world. 🚩", "reaction": "🥊"},
  {"id": 71, "number": "71", "text": "you had me at hello", "reply": "And you had me at our very first unfinished chess move. ♟️", "reaction": "👋"},
  {"id": 72, "number": "72", "text": "All I dream of is your eyes", "reply": "Deep, warm, and filled with a universe of kindness. 🌌", "reaction": "👁️"},
  {"id": 73, "number": "73", "text": "All I long for is your smile.", "reply": "Then I will spend every single day finding new reasons to put that smile on your face. 😁", "reaction": "🌻"},
  {"id": 74, "number": "74", "text": "darling that is enough", "reply": "You are more than enough. You are everything. 🌸", "reaction": "🕊️"},
  {"id": 75, "number": "75", "text": "you can say that I'm a fool for you", "reply": "Then we are two fools hopelessly, madly in love together. 🃏", "reaction": "🎪"},
  {"id": 76, "number": "76", "text": "your voice is my fav", "reply": "I could listen to your voice notes on loop all day long and never get tired. 🎙️", "reaction": "🎧"},
  {"id": 77, "number": "77", "text": "I'm really glad its you", "reply": "Out of 8 billion people on this planet, my heart picked you. 🌍", "reaction": "❤️"},
  {"id": 78, "number": "78", "text": "Its you its always gonna be you", "reply": "Lock it in. No doubts, no hesitations, forever. 🔐", "reaction": "💍"},
  {"id": 79, "number": "79", "text": "I never get tired of you", "reply": "Even after hours on the phone or days together, saying goodbye always hurts. ⏳", "reaction": "🫂"},
  {"id": 80, "number": "80", "text": "you make smile without trying", "reply": "Your happiness is infectious—when you light up, the whole world glows. ✨", "reaction": "☺️"},
  {"id": 81, "number": "81", "text": "you never let me sleep angry", "reply": "Because our love is too precious to waste a single night holding a grudge. 🌙", "reaction": "🛌"},
  {"id": 82, "number": "82", "text": "I'd choose you in every universe", "reply": "In a universe where we're kings, in one where we're birds, in every timeline—I will find you. 🌌", "reaction": "🪐"},
  {"id": 83, "number": "83", "text": "we are the best couple", "reply": "Unmatched chemistry, legendary banter, and endless romance. Unbeatable! 🏆", "reaction": "🥂"},
  {"id": 84, "number": "84", "text": "we are gonna be together forever.", "reply": "That's not just a hope, that's our master plan. 🗺️", "reaction": "📍"},
  {"id": 85, "number": "85", "text": "I hope we stay like this forever", "reply": "With every passing year, our love will only grow deeper, richer, and sweeter. 🍷", "reaction": "🕰️"},
  {"id": 86, "number": "86", "text": "I wanna be with you until we are old", "reply": "Sitting on a porch with wrinkled hands and grey hair, still laughing at the same silly jokes. 👵👴", "reaction": "☕"},
  {"id": 87, "number": "87", "text": "I'd rather annoy you forever", "reply": "Bring on the annoyances! I welcome all your chaotic energy for the rest of my days. 💥", "reaction": "🤪"},
  {"id": 88, "number": "88", "text": "No matter what its always", "reply": "Always us. Solid as a rock, unbreakable through every season. 🏔️", "reaction": "💎"},
  {"id": 89, "number": "89", "text": "I like us more than words", "reply": "Words on paper can only capture a tiny whisper of what we feel inside. 📖", "reaction": "🖋️"},
  {"id": 90, "number": "90", "text": "you are my fav plot twist", "reply": "The best surprise life ever handed me. I never saw you coming, and now I can't look away. 🎬", "reaction": "🎭"},
  {"id": 91, "number": "91", "text": "I love doing nothing with you", "reply": "Sitting in silence, scrolling next to each other, or sharing tea—nothingness is paradise with you. 🛋️", "reaction": "🍵"},
  {"id": 92, "number": "92", "text": "I'd pick you in every timeline", "reply": "Past, present, and future—I would cross every dimension to hold your hand. ⏳", "reaction": "🚀"},
  {"id": 93, "number": "93", "text": "Somehow you are my fav habit", "reply": "The best habit I'll never break. ☕", "reaction": "🌅"},
  {"id": 94, "number": "94", "text": "you are the first person I go to", "reply": "Whenever something great happens or something hurts, you are the first thought in my mind. 📲", "reaction": "🏃‍♂️"},
  {"id": 95, "number": "95", "text": "I love being your girl", "reply": "And I am the proudest, luckiest guy to call you mine. 👑", "reaction": "🎀"},
  {"id": 96, "number": "96", "text": "you are my everything", "reply": "My morning motivation, my daytime peace, and my bedtime dream. 🌤️", "reaction": "🌙"},
  {"id": 97, "number": "97", "text": "you are my destiny", "reply": "Written in the stars before we were even born. ✨", "reaction": "🔮"},
  {"id": 98, "number": "98", "text": "I see forever in your eyes", "reply": "When I look deep into your eyes, all my future plans suddenly make sense. 🔮", "reaction": "👁️"},
  {"id": 99, "number": "99", "text": "I love love cause its with you.", "reply": "You showed me what true, selfless, gentle love actually feels like. 🕊️", "reaction": "💖"},
  {"id": 100, "number": "100", "text": "you are my fav distraction", "reply": "Procrastinating by looking at your photos or texting you is my favorite hobby. 📱", "reaction": "🙈"},
  {"id": 101, "number": "101", "text": "you are my fav reason to stay up", "reply": "Those 2 AM deep talks about everything and nothing are memories I will cherish forever. 🌃", "reaction": "🦉"},
  {"id": 102, "number": "102", "text": "you are the reason behind my smile", "reply": "Seeing your text preview pop up makes me look like an idiot grinning at my phone in public! 😆", "reaction": "📱"},
  {"id": 103, "number": "103", "text": "I like your existence. A lot.", "reply": "And I am deeply, profoundly grateful for every second you exist in this world. 🌍", "reaction": "🙏"},
  {"id": 104, "number": "104", "text": "I'd always save you a seat", "reply": "Next to me is permanently reserved for you, always. 🪑", "reaction": "🎟️"},
  {"id": 105, "number": "105", "text": "you make me want to make memories", "reply": "Let's fill albums, walls, journals, and hard drives with our adventures together! 📷", "reaction": "✈️"},
  {"id": 106, "number": "106", "text": "I love our weird little universe", "reply": "Where our inside jokes, funny voices, and silly nicknames only make sense to the two of us. 🪐", "reaction": "👽"},
  {"id": 107, "number": "107", "text": "I like where we are", "reply": "Right here, right now—and where we're heading together. 🛤️", "reaction": "🌿"},
  {"id": 108, "number": "108", "text": "you are my fav coincidence", "reply": "Two classmates on a department shoot... who knew a chess board would begin forever? ♟️", "reaction": "🎲"},
  {"id": 109, "number": "109", "text": "you make my days fuller", "reply": "Rich with color, warmth, laughter, and purpose. 🎨", "reaction": "🌈"},
  {"id": 110, "number": "110", "text": "I will never hurt you", "reply": "I will guard your heart like the most priceless treasure in existence. 💎", "reaction": "🛡️"},
  {"id": 111, "number": "111", "text": "I'm glad you are my problem", "reply": "And you're my favorite problem to solve every single day! 🧩", "reaction": "🤓"},
  {"id": 112, "number": "112", "text": "I'd choose you on repeat", "reply": "Press replay, shuffle, loop—you're my favorite track on repeat forever. 🔁", "reaction": "🎵"},
  {"id": 113, "number": "113", "text": "I love being cheesy with you", "reply": "No cringe is too cringe when it's you and me being romantic. 🧀", "reaction": "🍕"},
  {"id": 114, "number": "114", "text": "I still have a huge crush on you", "reply": "Every time you dress up or look at me with that spark, my heart skips a beat. 💓", "reaction": "💃"},
  {"id": 115, "number": "115", "text": "you make my life more intresting", "reply": "No boring days allowed with us! Adventure is our default setting. 🎢", "reaction": "🗺️"},
  {"id": 116, "number": "116", "text": "I'd choose you over waffles", "reply": "Considering how much you worship sweet food, this is the highest honor in the universe! 🧇👑", "reaction": "🥞"},
  {"id": 117, "number": "117", "text": "I love being cringe with you", "reply": "Cringe together, stay together! Our silly moments are our most authentic. 🤪", "reaction": "✌️"},
  {"id": 118, "number": "118", "text": "you make my heart do dumb things", "reply": "Mine does backflips every time you say my name. 🤸‍♂️", "reaction": "💓"},
  {"id": 119, "number": "119", "text": "I will never get bored of you", "reply": "You are a masterpiece with endless chapters to explore. 📚", "reaction": "🎨"},
  {"id": 120, "number": "120", "text": "I like us exactly like this", "reply": "Authentic, slightly chaotic, deeply affectionate, and completely in love. 🖼️", "reaction": "✨"},
  {"id": 121, "number": "121", "text": "I like knowing you are mine", "reply": "The greatest badge of honor I will ever wear in this life. 🎖️", "reaction": "🏷️"},
  {"id": 122, "number": "122", "text": "you make even waiting worth it", "reply": "Distance or time doesn't matter when the destination is your warm hug. ⏳", "reaction": "🚉"},
  {"id": 123, "number": "123", "text": "you are worth losing sleep for", "reply": "Those late night calls where neither of us wants to hang up first are pure gold. 📞", "reaction": "🌙"},
  {"id": 124, "number": "124", "text": "I'd do anything for you", "reply": "And I would move mountains to see you achieve every dream in your heart. ⛰️", "reaction": "🦸‍♂️"},
  {"id": 125, "number": "125", "text": "I like having you in my life", "reply": "You turned my ordinary life into an extraordinary fairytale. 🏰", "reaction": "📖"},
  {"id": 126, "number": "126", "text": "TO me you are perfect", "reply": "Even your imperfections are perfect to me. You are flawless in my eyes. 🌺", "reaction": "👑"},
  {"id": 127, "number": "127", "text": "you are my greatest adventure", "reply": "More thrilling than any trip, more beautiful than any sunset. 🌄", "reaction": "🎒"},
  {"id": 128, "number": "128", "text": "you make me wanna be better", "reply": "You inspire me to grow, to be stronger, kinder, and the best man I can be. 🧗‍♂️", "reaction": "🌱"},
  {"id": 129, "number": "129", "text": "you are the one I wait for", "reply": "I would wait through rain, snow, and crowded metro platforms forever just to see your face. 🚉", "reaction": "🌧️"},
  {"id": 130, "number": "130", "text": "I look forward to meet you always", "reply": "Every single date feels just as exciting as the first day we met. 🌹", "reaction": "💐"},
  {"id": 131, "number": "131", "text": "wherever you go, I go", "reply": "Lead the way, my love. My heart will follow wherever your footsteps lead. 👣", "reaction": "🧭"},
  {"id": 132, "number": "132", "text": "you make me blush really hard", "reply": "Seeing your cheeks turn rosy red is the cutest sight in the entire world! 🙈❤️", "reaction": "🍅"},
  {"id": 133, "number": "133", "text": "you complete me", "reply": "You filled empty spaces in my heart I didn't even realize were waiting for you. 🧩", "reaction": "❤️"},
  {"id": 134, "number": "134", "text": "I'll never let you go", "reply": "Hold on tight, because I am holding on forever. 🤝", "reaction": "🔒"},
  {"id": 135, "number": "135", "text": "you are my happy ending", "reply": "The best ending, the greatest present, and an endless future. 🌅", "reaction": "🏁"},
  {"id": 136, "number": "136", "text": "All of me loves all of you", "reply": "Your curves, your edges, your moods, and every breath you take. 🎶", "reaction": "🎹"},
  {"id": 137, "number": "137", "text": "nothing compares to me", "reply": "Nothing and nobody on this earth could ever compare to you. 💎", "reaction": "👑"},
  {"id": 138, "number": "138", "text": "I can't help but falling in love with you", "reply": "Like wise men say, only fools rush in... and I am so glad I fell. 🎶", "reaction": "🌊"},
  {"id": 139, "number": "139", "text": "I only have eyes for you", "reply": "My vision blurs out the rest of the world whenever you walk into the room. 🕶️", "reaction": "👀"},
  {"id": 140, "number": "140", "text": "I'd find you again", "reply": "In any lifetime, in any world, under any stars—I will always search until I find you. 🌌", "reaction": "💫"},
    {"id": 141, "number": "141", "text": "you are always on my mind", "reply": "You live rent-free in my thoughts from the moment I wake up until my dreams take over. 💭❤️", "reaction": "🧠"},
  {"id": 142, "number": "142", "text": "I hope its always you", "reply": "It will always be you. Nobody else could ever come close to having my heart. 💖", "reaction": "💍"},
  {"id": 143, "number": "143", "text": "Lets never be a stranger", "reply": "Never. Even in a parallel universe, we'd look at each other and instantly remember. 🤝", "reaction": "🤝"},
  {"id": 144, "number": "144", "text": "You're the story id re-read", "reply": "Every chapter, every page, every single word—I could read our story a thousand times and never get tired. 📖", "reaction": "📚"},
  {"id": 145, "number": "145", "text": "If its you, I am in", "reply": "Count me in on everything too. Any adventure, any crazy plan, as long as it's with you. 🎟️", "reaction": "🚀"},
  {"id": 146, "number": "146", "text": "meet me where we begun", "reply": "Right by that unfinished chess board, with you smiling back at me. I'll meet you there every time. ♟️", "reaction": "♟️"},
  {"id": 147, "number": "147", "text": "I'd do anything to make you happy", "reply": "And your happiness is my whole world. Seeing your face glow makes everything worth it. ✨", "reaction": "🌟"},
  {"id": 148, "number": "148", "text": "you are my fav scent.", "reply": "And that soft perfume of yours is my absolute comfort zone whenever you cuddle close. 🌸", "reaction": "💐"},
  {"id": 149, "number": "149", "text": "you are my best kinda deja vu", "reply": "Because meeting you felt like reuniting with someone my soul had known for centuries. 🔮", "reaction": "✨"},
  {"id": 150, "number": "150", "text": "I hope this scene never ends", "reply": "I never want this movie to fade to black. Let's make this our infinite scene. 🎬", "reaction": "🎥"},
  {"id": 151, "number": "151", "text": "Lets be together and prove everyone wrong", "reply": "We will. Side by side, standing tall, proving that real love wins every single bet. 🏆", "reaction": "💪"},
  {"id": 152, "number": "152", "text": "Foreve isn't too long with you", "reply": "Forever actually feels too short with you—I'm gonna need an eternity and a half! ⏳", "reaction": "♾️"},
  {"id": 153, "number": "153", "text": "You're the part I'd never skip", "reply": "And you are the melody I put on repeat all day long. 🎵", "reaction": "🎧"},
  {"id": 154, "number": "154", "text": "I'd recognise your soul.", "reply": "Even in a sea of eight billion people, my soul would find yours in a heartbeat. 🌌", "reaction": "💫"},
  {"id": 155, "number": "155", "text": "I'd stay if you want to me", "reply": "I want you to stay forever. Don't you dare go anywhere, silly! 🏡", "reaction": "🤍"},
  {"id": 156, "number": "156", "text": "you always make fell safe", "reply": "My arms are your sanctuary. No storm from the outside world can touch you here. 🛡️", "reaction": "🧸"},
  {"id": 157, "number": "157", "text": "I want more time with", "reply": "...with me! Haha you didn't even have to finish the sentence—all of my time belongs to you. ⏰", "reaction": "⏳"},
  {"id": 158, "number": "158", "text": "I'd look for you in th crowd", "reply": "And my eyes will be looking right back, cutting through the entire crowd straight to you. 👀", "reaction": "🎯"},
  {"id": 159, "number": "159", "text": "If forever exists, I hope its with you", "reply": "Forever exists because we're creating it together, one beautiful memory at a time. 🌅", "reaction": "♾️"},
  {"id": 160, "number": "160", "text": "I hope my 7 minutes is you", "reply": "If that scientific theory is true, all 7 minutes of my brain activity will be pure memories of your smile. 💭❤️", "reaction": "🧠"},
  {"id": 161, "number": "161", "text": "you are the love i would remember", "reply": "And you are the only love etched permanently into every fiber of my being. 💌", "reaction": "📜"},
  {"id": 162, "number": "162", "text": "Please dont become a memory", "reply": "Never. I am your living, breathing present and your future. I am staying right here. 🔒", "reaction": "⚓"},
  {"id": 163, "number": "163", "text": "I want to be yours always", "reply": "You are mine, and I am yours—irrevocably, completely, and forever. 💍", "reaction": "❤️"},
  {"id": 164, "number": "164", "text": "I don't want a version of me without you", "reply": "And I don't ever want a universe where Vishal isn't loving you. We belong together. 🌌", "reaction": "🪐"},
  {"id": 165, "number": "165", "text": "I want you to remember us forever", "reply": "I will remember every glance, every laugh, and every touch for the rest of my days. 🕯️", "reaction": "🌟"},
  {"id": 166, "number": "166", "text": "One day I hope we tell our kids our story", "reply": "I can already hear us arguing over who fell for who first, telling them about our unfinished chess match! ♟️❤️", "reaction": "👨‍👩‍👧"},
  {"id": 167, "number": "167", "text": "I want years nobody writes about", "reply": "Quiet years, cozy mornings, boring grocery runs, wrinkly smiles—the sweet everyday magic just for us. 🏡", "reaction": "☕"},
  {"id": 168, "number": "168", "text": "I hope old us holds hand", "reply": "We will be that adorable 80-year-old couple sitting on a bench holding hands, still teasing each other. 👵👴❤️", "reaction": "👵👴"},
  {"id": 169, "number": "169", "text": "I cannot imagine my life without you", "reply": "Neither can I. You became my whole world before I even realized what was happening. 🌍", "reaction": "💫"},
  {"id": 170, "number": "170", "text": "Lastly, I love you, and I always will", "reply": "Lastly, and always: I love you more than words, code, or songs could ever express. Happy Birthday, my love. Forever and always. ❤️", "reaction": "💖"}
];
